name = "slop-create-server"
author = "crystalmathw"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cbbcb7db7948866b3780619fb19349cc5cc923a5b6b418173c30fa237d4526be"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
acceptable-game-versions = ["1.21.1"]
