name = "slop-create-server"
author = "crystalmathw"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63b8b4aa36c1b80b876be4e67a183095af49a0895fe56b15a06fa05a2f120f16"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
acceptable-game-versions = ["1.21.1"]
