name = "slop-create-server"
author = "crystalmathw"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5be4020dca40051e72a01fcaeb8e8e7b1850ccf92c1afa4ba19a8a87634d60a1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"

[options]
acceptable-game-versions = ["1.21.1"]
